# TOML file for building tne `nighthawk` package.
#
# This file is modeled after a similar file in the Python packaging
# tutorial at
# https://packaging.python.org/en/latest/tutorials/packaging-projects/.
#
# To create a Python environment named `nighthawk-dev` in which to work
# on the `nighthawk` package:
#
#     conda create -n nighthawk-dev python=3.10
#     conda activate nighthawk-dev
#     pip install -e <nighthawk package dir path>
#
# To build the `nighthawk` package, activate a Python environment that
# includes the `build` package and issue the following command from
# within the directory containing this TOML file:
#
#     python -m build

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nighthawk"
version = "0.0.0"
authors = [
  { name="Benjamin Van Doren", email="vandoren@cornell.edu" },
]
description = "Nighthawk avian nocturnal flight call detector"
# readme = "README.md"
# license = {file = "LICENSE.txt"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = "~=3.10.0"

dependencies = [

    "jupyter",
    "librosa~=0.9.0",
    "pandas",

    # The scikit-learn package version number should match exactly
    # that of the version that saved the sigmoid probability
    # calibrators. Otherwise scikit-learn will issue a warning every
    # time the detector runs.
    "scikit-learn==1.0.1",

    "tensorflow~=2.11.0"

]

[project.urls]
"Homepage" = "https://github.com/bmvandoren/nighthawk"
"Bug Tracker" = "https://github.com/bmvandoren/nighthawk/issues"

[project.scripts]
nighthawk = "nighthawk.run_nighthawk:main"
